apiVersion: v1
kind: Service
metadata:
  name: {{ template "mail-server.fullname" . }}-mail
  labels:
    app: {{ template "mail-server.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: {{ .Values.service.name }}-smtp
      port: {{ default 25 .Values.service.externalPort.smtp }}
      targetPort: {{ default 25 .Values.service.internalPort.smtp }}
      protocol: TCP
    - name: {{ .Values.service.name }}-pop3
      port: {{ default 110 .Values.service.externalPort.pop3 }}
      targetPort: {{ default 110 .Values.service.internalPort.pop3 }}
      protocol: TCP
    - name: {{ .Values.service.name }}-imap
      port: {{ default 143 .Values.service.externalPort.imap }}
      targetPort: {{ default 143 .Values.service.internalPort.imap }}
      protocol: TCP
    - name: {{ .Values.service.name }}-smtps
      port: {{ default 465 .Values.service.externalPort.smtps }}
      targetPort: {{ default 465 .Values.service.internalPort.smtps }}
      protocol: TCP
    - name: {{ .Values.service.name }}-msa
      port: {{ default 587 .Values.service.externalPort.msa }}
      targetPort: {{ default 587 .Values.service.internalPort.msa }}
      protocol: TCP
    - name: {{ .Values.service.name }}-imaps
      port: {{ default 993 .Values.service.externalPort.imaps }}
      targetPort: {{ default 993 .Values.service.internalPort.imaps }}
      protocol: TCP
    - name: {{ .Values.service.name }}-pop3s
      port: {{ default 995 .Values.service.externalPort.pop3s }}
      targetPort: {{ default 995 .Values.service.internalPort.pop3s }}
      protocol: TCP
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
  selector:
    app: {{ template "mail-server.name" . }}
    release: {{ .Release.Name }}
